"""major

Revision ID: 1476905000cb
Revises: b48658c834ca
Create Date: 2020-02-16 10:06:03.850955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1476905000cb'
down_revision = 'b48658c834ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('major', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'major')
    # ### end Alembic commands ###
